main: dev.vankka.placeholdersplus.plugin.bukkit.PlaceholdersPlusBukkit
name: PlaceholdersPlus
version: @VERSION@
author: Vankka
api-version: 1.13

commands:
  placeholdersplus:
    aliases: ["pplus"]
    description: Main command for PlaceholdersPlus

permissions:
  placeholdersplus.download.base:
    default: op
  placeholdersplus.download.full:
    default: op
